-- ============================================================
-- 유연 변호사 홈페이지 — 콘텐츠 스키마 + 보안(RLS)
-- Supabase Dashboard → SQL Editor 에 붙여넣고 Run 한 번.
-- 재실행해도 안전하도록 작성(idempotent).
--
-- 보안 원칙
--   · 공개(anon): 콘텐츠 테이블은 읽기(SELECT)만.
--   · 쓰기(INSERT/UPDATE/DELETE): 아래 admin_uid 계정만(심층 방어).
--     설령 누군가 self-signup 하더라도 그 uid가 아니면 쓰기 불가.
--   · inquiries(상담 문의)는 반대다 — anon 은 INSERT 만, 읽기는 관리자만.
--     개인정보가 들어가는 테이블이므로 공개 읽기를 절대 열지 않는다.
--   · Authentication → Providers 에서 공개 signup 비활성화 권장.
--
-- 데이터 우선순위
--   앱은 이 테이블들을 1순위로 읽고, 비어 있거나 오류이면
--   src/data/*.ts + cv.generated.json (CV 정본)으로 폴백한다.
--   즉 DB를 비워 두어도 사이트는 정상 동작한다.
-- ============================================================

-- updated_at 자동 갱신
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

-- ---------- profile (단일 행: id = 1) ----------
create table if not exists public.profile (
  id int primary key default 1,
  name_ko text, name_en text, title text,
  affiliation text, affiliation_en text,
  tagline text, lede text, creed text,
  intro jsonb default '[]'::jsonb,
  stats jsonb default '[]'::jsonb,
  metrics jsonb default '[]'::jsonb,
  contact jsonb default '{}'::jsonb,
  updated_at timestamptz default now(),
  constraint profile_singleton check (id = 1)
);

-- ---------- timeline (학력 · 자격 · 경력) ----------
create table if not exists public.timeline (
  id bigint generated by default as identity primary key,
  kind text not null,                    -- 'education' | 'credential' | 'career'
  period text, title text, note text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists timeline_kind_idx on public.timeline (kind, sort_order);

-- ---------- practice_areas (업무분야) ----------
create table if not exists public.practice_areas (
  id bigint generated by default as identity primary key,
  key text unique not null,
  no text, title text, summary text, detail text,
  tags jsonb default '[]'::jsonb,
  cv_sections jsonb default '[]'::jsonb,  -- 근거가 되는 CV 사건 섹션 번호
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- cases (수행사건) ----------
-- ⚠️ 당사자명·사건번호를 넣지 않는다. CV 익명화 원칙을 DB에서도 지킨다.
create table if not exists public.cases (
  id bigint generated by default as identity primary key,
  section_no text not null,               -- '04' ~ '14'
  section_title text,
  text text not null,
  outcome text,                           -- '피고 대리 · 승소', '진행 중' 등
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists cases_section_idx on public.cases (section_no, sort_order);

-- ---------- notes (기업법 노트 · 발행 원고) ----------
create table if not exists public.notes (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  title text not null,
  series_key text default 'essay',        -- 'corporate' | 'essay' | 'ipfinance'
  series_label text,
  dek text,
  summary jsonb default '[]'::jsonb,      -- 3줄 요약
  tags jsonb default '[]'::jsonb,
  body text,
  published_at date,
  is_published boolean default true,
  source_file text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists notes_pub_idx on public.notes (is_published, published_at desc);

-- ---------- writings (저술 · 연재 · 강연) ----------
create table if not exists public.writings (
  id bigint generated by default as identity primary key,
  group_name text, text text not null, outcome text,
  sort_order int default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- ---------- inquiries (상담 문의 접수) ----------
-- 개인정보 테이블. 공개 읽기를 열지 않는다.
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  contact text not null,
  category text,
  message text not null,
  status text default 'new',              -- 'new' | 'replied' | 'closed'
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
create index if not exists inquiries_new_idx on public.inquiries (status, created_at desc);

-- ============================================================
-- RLS
-- ============================================================
do $$
declare
  t text;
  -- 관리자 uid. scripts/create-admin.mjs 로 계정을 만든 뒤 이 값을 교체하고 다시 실행한다.
  admin_uid constant text := '00000000-0000-0000-0000-000000000000';
begin
  -- 공개 읽기 + 관리자 쓰기
  foreach t in array array[
    'profile','timeline','practice_areas','cases','notes','writings'
  ] loop
    execute format('alter table public.%I enable row level security;', t);

    execute format('drop policy if exists %I on public.%I;', t||'_public_read', t);
    execute format(
      'create policy %I on public.%I for select to anon, authenticated using (true);',
      t||'_public_read', t);

    execute format('drop policy if exists %I on public.%I;', t||'_admin_write', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (auth.uid() = %L) with check (auth.uid() = %L);',
      t||'_admin_write', t, admin_uid, admin_uid);

    execute format('drop trigger if exists %I on public.%I;', t||'_set_updated_at', t);
    execute format(
      'create trigger %I before update on public.%I for each row execute function public.set_updated_at();',
      t||'_set_updated_at', t);
  end loop;

  -- inquiries: anon 은 INSERT 만, 읽기·수정은 관리자만
  execute 'alter table public.inquiries enable row level security;';

  execute 'drop policy if exists inquiries_public_insert on public.inquiries;';
  execute 'create policy inquiries_public_insert on public.inquiries
             for insert to anon, authenticated with check (true);';

  execute 'drop policy if exists inquiries_admin_read on public.inquiries;';
  execute format(
    'create policy inquiries_admin_read on public.inquiries
       for select to authenticated using (auth.uid() = %L);', admin_uid);

  execute 'drop policy if exists inquiries_admin_write on public.inquiries;';
  execute format(
    'create policy inquiries_admin_write on public.inquiries
       for update to authenticated using (auth.uid() = %L) with check (auth.uid() = %L);',
    admin_uid, admin_uid);

  execute 'drop trigger if exists inquiries_set_updated_at on public.inquiries;';
  execute 'create trigger inquiries_set_updated_at before update on public.inquiries
             for each row execute function public.set_updated_at();';
end $$;
